[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bank_app = "BAVmCey5z82YthtpaEm4cfh9vU4KwdRiz2A7tx9oQLKD"
staking_app = "r3UZz8WUnn8endrpQbkPJaKruUYNeeTc5NFYroGcc6a"

[programs.localnet]
bank_app = "3q57ftWH75aKfxoNnV6Lu1n8LhV73xxKHAxPapL6Jvh7"
staking_app = "EYdKY4wWuwNr7uVRQNBUEXeJyLCAatSELPck3quW7JvA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/bank-app.ts"
