[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
my_first_anchor_project = "GDGNBNAhHGmMKcxVxXBTTJ8xytmdjNuFWsr2igqhck27"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
